#!/bin/sh

start() {
	# Adjuist voltage scale for adc-key buttons.
	cat /sys/bus/iio/devices/iio:device0/in_voltage0_scale_available | \
		cut -d' ' -f2 >/sys/bus/iio/devices/iio:device0/in_voltage0_scale
}

stop() {
	# Switch voltage scale for adc-key buttons back to default.
	cat /sys/bus/iio/devices/iio:device0/in_voltage0_scale_available | \
		cut -d' ' -f1 >/sys/bus/iio/devices/iio:device0/in_voltage0_scale
}

restart() {
	stop
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
